MAQUINAS = {
    "MAQ-01": {
        "codigo": "MAQ-01",
        "nombre": "Torno 03",
        "marca": "Mazak",
        "modelo": "QUICK TURN 200",
        "ubicacion": "Planta 1",
        "estado": "Operativa",
        "proxima_inspeccion": "12 de Septiembre de 2026",
        "ultima_inspeccion": "12 de Agosto de 2026",
        "hallazgos_abiertos": "2",
    },
    "MAQ-02": {
        "codigo": "MAQ-02",
        "nombre": "Fresadora 01",
        "marca": "DMG Mori",
        "modelo": "CMX 600 V",
        "ubicacion": "Planta 2",
        "estado": "Operativa",
        "proxima_inspeccion": "18 de Septiembre de 2026",
        "ultima_inspeccion": "18 de Agosto de 2026",
        "hallazgos_abiertos": "0",
    },
    "MAQ-03": {
        "codigo": "MAQ-03",
        "nombre": "Prensa 02",
        "marca": "Haas",
        "modelo": "VF-2",
        "ubicacion": "Planta 1",
        "estado": "Mantenimiento",
        "proxima_inspeccion": "25 de Septiembre de 2026",
        "ultima_inspeccion": "25 de Agosto de 2026",
        "hallazgos_abiertos": "1",
    },
}
